spring.application.name=tienda

# Puerto 80 permite acceder como "localhost" sin número de puerto
server.port=80

# Formato de hora en el log de la consola
logging.pattern.dateformat=hh:mm

# Elimina el banner de Spring al arrancar
spring.main.banner-mode=off

# En desarrollo usar false; en producción cambiar a true
spring.thymeleaf.cache=false